"""Row-count reconciliation callable for ``warehouse_daily_batch_pipeline`` (P2.5).

Compares current Gold mart row counts to a stored baseline (the previous
successful run's row counts) and warns on day-over-day delta exceeding a
configurable threshold (default 20%).

This catches:
* Silent data loss — upstream dropped a partition, ``fact_sales`` dropped 50%.
* Volume spikes — a backfill ran, ``fact_sales`` grew 500%.
* Stale dims — ``dim_date`` not advancing, ``dim_customer`` frozen at 0 rows.

Baseline persistence
--------------------
The baseline is stored as an Airflow Variable (``gold_row_counts_baseline``)
containing a JSON map of ``"schema.table": row_count``. The baseline is
updated *only* on a clean run (no warnings). On a warned run, the previous
baseline is preserved so the next run still compares against the last known
good state.

Configuration (Airflow Variables)
---------------------------------
* ``gold_row_counts_baseline`` — JSON map; default ``"{}"`` (empty — first run
  establishes the baseline without warning).
* ``row_count_delta_threshold`` — float in [0, 1]; default ``0.20`` (20%).

Both variables are optional; the callable uses the defaults if absent. They
should be seeded in the MWAA UI per environment — see
``scripts/cloud/deploy_platform.ps1 -Action airflow-vars`` for the manual entries.

Wiring
------
Imported by ``orchestration/airflow/dags/warehouse_daily_batch_pipeline.py`` as a
``PythonOperator`` placed after ``dbt_tests`` and before ``ge_checkpoint``.
The task does NOT fail the DAG on a warning — it logs at WARNING level so
operators see it in the Airflow UI without breaking the pipeline. Fail-fast
behavior can be added later by raising an exception when ``warned=True``.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from typing import Any

log = logging.getLogger(__name__)

DEFAULT_THRESHOLD = 0.20
BASELINE_VAR_NAME = "gold_row_counts_baseline"
THRESHOLD_VAR_NAME = "row_count_delta_threshold"

# Gold marts to reconcile. Order matters only for log readability.
# (schema, table) — must match the schemas generated by generate_schema_name.sql
# and the Redshift DDL under transformation/redshift/ddl/.
GOLD_MARTS: list[tuple[str, str]] = [
    ("finance", "dim_date"),
    ("finance", "dim_store"),
    ("finance", "fact_sales"),
    ("finance", "fact_inventory_snapshot"),
    ("marketing", "dim_customer"),
    ("marketing", "dim_product"),
    ("marketing", "identity_graph"),
    ("marketing", "fact_customer_session"),
    ("summary", "sales_daily_store"),
    ("summary", "inventory_daily_product_store"),
    ("summary", "sessions_daily_platform"),
]


@dataclass(frozen=True)
class MartRowCount:
    schema: str
    table: str
    row_count: int


def _query_row_counts(conn: Any) -> list[MartRowCount]:
    """SELECT COUNT(*) from each Gold mart. Missing/unqueryable tables -> -1.

    Errors are logged at WARNING and recorded as -1 so the reconciliation
    still produces a full report instead of aborting on the first failure.
    """
    results: list[MartRowCount] = []
    with conn.cursor() as cur:
        for schema, table in GOLD_MARTS:
            try:
                cur.execute(f"SELECT COUNT(*) FROM {schema}.{table}")
                row = cur.fetchone()
                count = int(row[0]) if row and row[0] is not None else -1
            except Exception as exc:  # noqa: BLE001
                log.warning("Failed to query %s.%s: %s", schema, table, exc)
                count = -1
            results.append(MartRowCount(schema, table, count))
    return results


def _load_baseline(var_get: Any) -> dict[str, int]:
    """Load the baseline map. ``var_get`` is ``airflow.models.Variable.get``.

    Injected as a parameter so unit tests can stub it without monkeypatching
    the Airflow module.
    """
    raw = var_get(BASELINE_VAR_NAME, default_var="{}")
    try:
        parsed = json.loads(raw) if raw else {}
        return {k: int(v) for k, v in parsed.items()}
    except (json.JSONDecodeError, ValueError, TypeError) as exc:
        log.warning("Baseline parse failed (%s); starting fresh", exc)
        return {}


def _save_baseline(var_set: Any, baseline: dict[str, int]) -> None:
    """Persist the baseline as JSON."""
    var_set(BASELINE_VAR_NAME, json.dumps(baseline))


def _resolve_threshold(var_get: Any) -> float:
    raw = var_get(THRESHOLD_VAR_NAME, default_var=str(DEFAULT_THRESHOLD))
    try:
        val = float(raw)
    except (ValueError, TypeError):
        return DEFAULT_THRESHOLD
    # Clamp to [0, 1] — values outside this range are nonsensical.
    return max(0.0, min(1.0, val))


def _delta_pct(prev: int | None, current: int) -> float | None:
    """Day-over-day delta as a fraction. None if uncomputable."""
    if prev is None or prev <= 0 or current < 0:
        return None
    return (current - prev) / prev


def reconcile_gold_row_counts(
    *,
    conn: Any,
    var_get: Any,
    var_set: Any,
) -> dict[str, Any]:
    """Compare current Gold mart row counts to baseline; warn on >threshold delta.

    Returns a dict with per-mart deltas and a ``warned`` flag. Updates the
    baseline only if no mart exceeded the threshold (preserves last known good
    on a warned run).
    """
    current = _query_row_counts(conn)
    baseline = _load_baseline(var_get)
    threshold = _resolve_threshold(var_get)

    deltas: dict[str, dict[str, Any]] = {}
    warned = False
    for mart in current:
        key = f"{mart.schema}.{mart.table}"
        prev = baseline.get(key)
        delta_pct = _delta_pct(prev, mart.row_count)
        if delta_pct is not None and abs(delta_pct) > threshold:
            warned = True
            log.warning(
                "Row-count delta for %s: %d -> %d (%+.1f%% > %.0f%% threshold)",
                key,
                prev if prev is not None else -1,
                mart.row_count,
                delta_pct * 100,
                threshold * 100,
            )
            status = "WARN"
        elif delta_pct is None:
            status = "no_baseline" if prev is None else "unavailable"
            log.info(
                "Row-count delta for %s: prev=%s current=%d (%s)",
                key,
                prev,
                mart.row_count,
                status,
            )
        else:
            status = "ok"
            log.info(
                "Row-count delta for %s: prev=%d current=%d (%+.1f%%)",
                key,
                prev if prev is not None else -1,
                mart.row_count,
                delta_pct * 100,
            )

        deltas[key] = {
            "previous": prev,
            "current": mart.row_count,
            "delta_pct": delta_pct,
            "status": status,
        }

    if not warned:
        new_baseline = {f"{m.schema}.{m.table}": m.row_count for m in current}
        _save_baseline(var_set, new_baseline)
        log.info("Baseline updated (no warnings).")
    else:
        log.warning(
            "Baseline NOT updated — investigate warnings before next run. "
            "Previous baseline preserved for next comparison."
        )

    return {"warned": warned, "threshold": threshold, "deltas": deltas}


def _emit_metadata(result: dict[str, Any], context: dict[str, Any] | None) -> None:
    """Best-effort DQ rows into the metadata database (fail-open)."""
    try:
        from metadata_airflow import _observer, _writer, execution_id_for_context

        observer = _observer()
        if observer is None:
            return
        writer = _writer(observer)
        if writer is None:
            return
        try:
            execution_id = (
                execution_id_for_context(context or {})
                if context
                else "row_count_reconciliation"
            )
            observer.record_reconciliation_results(
                writer,
                execution_id=execution_id,
                deltas=result.get("deltas") or {},
                warned=bool(result.get("warned")),
            )
        finally:
            writer.close()
    except Exception as exc:  # noqa: BLE001
        log.warning("metadata emit from reconciliation failed (fail-open): %s", exc)


def _airflow_entrypoint(**context: Any) -> dict[str, Any]:
    """Airflow PythonOperator entrypoint.

    Reads Redshift creds + baseline Variable from the Airflow runtime.
    Kept thin so the reconciliation logic itself is testable without Airflow.
    """
    import redshift_connector
    from airflow.models import Variable

    from metadata_airflow import redshift_password

    conn = redshift_connector.connect(
        host=Variable.get("redshift_host"),
        port=int(Variable.get("redshift_port", default_var="5439")),
        database=Variable.get("redshift_database", default_var="prod"),
        user=Variable.get("redshift_user"),
        password=redshift_password(),
    )
    try:
        result = reconcile_gold_row_counts(
            conn=conn,
            var_get=Variable.get,
            var_set=Variable.set,
        )
        _emit_metadata(result, context)
        return result
    finally:
        conn.close()


# Airflow PythonOperator callable — referenced by warehouse_daily_batch_pipeline.py.
# The double-underscore name signals "do not import in tests"; tests should
# import ``reconcile_gold_row_counts`` and inject ``conn``/``var_get``/``var_set``
# doubles.
reconcile_gold_row_counts_task = _airflow_entrypoint
