"""P2.1 — dbt incremental idempotency test.

For each incremental model in the local DuckDB identity chain, runs
``dbt run --full-refresh`` followed by ``dbt run`` (incremental, no
full-refresh) and asserts that row counts are unchanged. Catches
regressions where an incremental lookback window drops rows on the
second run (too narrow) or duplicates them (missing ``unique_key`` /
``delete+insert`` strategy).

Scope
-----
The identity chain is the only set of models that works end-to-end in the
local DuckDB sim (Bronze seeds under ``seeds/bronze/`` plus the generated
``seeds/silver/identity_resolution.csv`` fixture provide the upstream
sources):

* ``intermediate.int_identity_public_devices``
* ``intermediate.int_identity_resolution``  (view over the Spark source, ADR-010)
* ``marketing.identity_graph``

The edge/component builders retired in ADR-010 (Spark GraphFrames) are
covered by ``tests/unit/test_spark_identity_resolution.py``.

Other Gold marts (``fact_sales``, ``fact_inventory_snapshot``,
``fact_customer_session``, ``dim_customer``) read from sources that the
local DuckDB sim does not seed (Bronze/Silver Parquet via Spectrum);
idempotency for those is verified in the live-Redshift integration
suite under ``quality/pytest/``.

Flink job idempotency is deferred until a local Flink test harness
exists — see ``docs/runbooks/dw-checklist-audit.md`` P2.1 note.

Run
---
    pip install "dbt-core==1.11.*" "dbt-duckdb>=1.10,<2.0" "duckdb>=1.5,<2.0"
    pytest tests/integration/test_dbt_idempotency.py -v -m integration_duckdb
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

pytestmark = [
    pytest.mark.integration_duckdb,
    pytest.mark.skipif(
        shutil.which("dbt") is None,
        reason="dbt not installed (pip install dbt-duckdb)",
    ),
    pytest.mark.skipif(
        shutil.which("python") is None,
        reason="python interpreter missing from PATH",
    ),
]

# (schema, table) — must match the schemas generated by generate_schema_name.sql
IDENTITY_CHAIN_TABLES: list[tuple[str, str]] = [
    ("intermediate", "int_identity_public_devices"),
    ("intermediate", "int_identity_resolution"),
    ("marketing", "identity_graph"),
]


def _dbt_target_local(*args: str, cwd: Path) -> subprocess.CompletedProcess:
    """Run a dbt subcommand against the local DuckDB target."""
    cmd = [
        "dbt",
        *args,
        "--profiles-dir",
        str(cwd),
        "--target",
        "local",
    ]
    print(f"[dbt] {' '.join(cmd)} (cwd={cwd})")
    return subprocess.run(
        cmd,
        cwd=str(cwd),
        check=False,
        text=True,
        capture_output=True,
    )


def _assert_dbt_success(result: subprocess.CompletedProcess, label: str) -> None:
    if result.returncode != 0:
        pytest.fail(
            f"dbt {label} failed (exit={result.returncode}):\n"
            f"--- stdout ---\n{result.stdout}\n"
            f"--- stderr ---\n{result.stderr}"
        )


def _row_counts(duckdb_path: Path) -> dict[str, int]:
    """Snapshot row counts of all identity chain tables from the DuckDB file."""
    import duckdb

    if not duckdb_path.exists():
        return {f"{s}.{t}": -1 for s, t in IDENTITY_CHAIN_TABLES}

    counts: dict[str, int] = {}
    con = duckdb.connect(str(duckdb_path), read_only=True)
    try:
        for schema, table in IDENTITY_CHAIN_TABLES:
            key = f"{schema}.{table}"
            try:
                row = con.execute(
                    f"SELECT COUNT(*) FROM {schema}.{table}"
                ).fetchone()
                counts[key] = int(row[0]) if row and row[0] is not None else -1
            except Exception as exc:  # noqa: BLE001
                # Table missing or schema not built — record as -1 so the
                # test surfaces the regression clearly.
                counts[key] = -1
                print(f"[row_counts] {key}: query failed ({exc})")
    finally:
        con.close()
    return counts


def test_identity_chain_idempotent(
    dbt_project_dir: Path,
    duckdb_path: Path,
) -> None:
    """Run the identity chain twice; assert row counts are identical.

    The first run uses ``--full-refresh`` (clean slate, baseline). The
    second run is incremental (no ``--full-refresh``). For a correctly
    written incremental model with ``delete+insert`` + ``unique_key``,
    the second run re-processes the same upstream data and lands the
    same row set, so row counts must match.
    """
    # Clean slate: remove any stale DuckDB file from a prior dev run.
    if duckdb_path.exists():
        duckdb_path.unlink()
    wal = duckdb_path.with_suffix(".duckdb.wal")
    if wal.exists():
        wal.unlink()

    # 1. dbt deps + seed + full-refresh run (baseline)
    _assert_dbt_success(_dbt_target_local("deps", cwd=dbt_project_dir), "deps")
    _assert_dbt_success(_dbt_target_local("seed", cwd=dbt_project_dir), "seed")
    _assert_dbt_success(
        _dbt_target_local(
            "run",
            "--select",
            "+identity_graph",
            "--full-refresh",
            cwd=dbt_project_dir,
        ),
        "run --full-refresh",
    )

    baseline_counts = _row_counts(duckdb_path)
    print(f"[baseline] {baseline_counts}")

    # Sanity: at least the leaf model should have rows. If it's -1 or 0,
    # the chain didn't build — fail loudly rather than passing vacuously.
    assert baseline_counts["marketing.identity_graph"] > 0, (
        "identity_graph has 0 rows after full-refresh — chain did not build "
        f"(counts: {baseline_counts})"
    )

    # 2. Second run — incremental, no --full-refresh. Idempotency check.
    _assert_dbt_success(
        _dbt_target_local(
            "run",
            "--select",
            "+identity_graph",
            cwd=dbt_project_dir,
        ),
        "run (incremental)",
    )

    after_counts = _row_counts(duckdb_path)
    print(f"[after]    {after_counts}")

    # 3. Assert each table has identical row counts.
    mismatches: list[str] = []
    for schema, table in IDENTITY_CHAIN_TABLES:
        key = f"{schema}.{table}"
        before = baseline_counts.get(key, -1)
        after = after_counts.get(key, -1)
        if before != after:
            mismatches.append(f"  {key}: {before} -> {after} (delta={after - before})")

    assert not mismatches, (
        "Idempotency regression — row counts changed on second (incremental) run:\n"
        + "\n".join(mismatches)
        + "\nLikely cause: an incremental lookback window that is too narrow "
        "(drops rows) or missing unique_key / delete+insert strategy (duplicates)."
    )
